AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your Docker-based function.

Resources:
  hopBeResource:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: hop-be-function-native-image
      PackageType: Image
      MemorySize: 512
      Timeout: 90
      Architectures:
        - x86_64
      ImageUri: ghcr.io/hopoasis/hop_oasis_be:latest
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:eu-central-1:851725266218:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - >-
                  arn:aws:logs:eu-central-1:851725266218:log-group:/aws/lambda/hop-be:*
      SnapStart:
        ApplyOn: None
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
