CREATE TABLE IF NOT EXISTS user
( id INTEGER NOT NULL AUTO_INCREMENT,
  email VARCHAR(256) NOT NULL,
  password VARCHAR(256) NOT NULL,
  role VARCHAR(256) NOT NULL,
  user_details VARCHAR(256) NOT NULL,
  PRIMARY KEY (id)
);
