CREATE TABLE IF NOT EXISTS cider_images(
    id BIGINT  PRIMARY KEY AUTO_INCREMENT,
    image LONGBLOB NOT NULL,
    name VARCHAR(500) NOT NULL,
    cider_id BIGINT,
    CONSTRAINT fk_cider FOREIGN KEY (cider_id) REFERENCES cider(id) ON DELETE CASCADE

);