CREATE TABLE IF NOT EXISTS snacks_images(
    id BIGINT  PRIMARY KEY AUTO_INCREMENT,
    image LONGBLOB NOT NULL,
    name VARCHAR(500) NOT NULL,
    snack_id BIGINT,
    CONSTRAINT fk_snacks FOREIGN KEY (snack_id) REFERENCES snacks(id) ON DELETE CASCADE

);