CREATE TABLE IF NOT EXISTS products_bundle (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    price DECIMAL(7, 2) NOT NULL,
    description VARCHAR(1500) NOT NULL

);