name: CICD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          java-package: 'jdk'
          check-latest: false
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true
          job-status: success
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_LOGIN}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t roananik/hopoasis .
      - name: Publish image to docker hub
        run: docker push roananik/hopoasis:latest
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Delete old container
        run: docker rm -f hopoasis-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name hopoasis-container roananik/hopoasis

