name: CICD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          java-package: 'jdk'
          check-latest: false
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true
          job-status: success
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_LOGIN}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t roananik/hopoasis .
      - name: Publish image to docker hub
        run: docker push roananik/hopoasis:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Pull docker image from Docker Hub on EC2 instance
        run: ssh -o StrictHostKeyChecking=no ec2-user@<EC2_INSTANCE_IP> 'docker pull roananik/hopoasis:latest'
      - name: Copy docker-compose.yml to EC2
        run: scp -o StrictHostKeyChecking=no docker-compose.yml ec2-user@<secrets.AWS_EC2_INSTANS_IP>:~/docker-compose.yml

      - name: Run Docker Compose on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@<secrets.AWS_EC2_INSTANS_IP> 'docker-compose -f ~/docker-compose.yml up -d'
