name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build Project
        run: mvn clean package -DskipTests

      - name: Package application
        run: |
          mkdir -p build/distributions
          cp target/hop_oasis.jar build/distributions/
          zip -r build/distributions/my-app.zip target/hop_oasis.jar .ebextensions

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'hop_be'
          environment_name: 'prod'
          version_label: ${{ github.sha }}
          region: eu-central-1
          deployment_package: build/distributions/my-app.zip
