name: Maven build and Docker push

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

     
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          java-package: 'jdk'
          check-latest: false
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true
          job-status: success

     
      - name: Build with Maven and run tests
        run: mvn clean verify

     
      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose
        continue-on-error: true

      
      - name: Check Docker and Docker Compose installation
        run: docker --version && docker-compose --version

     
      - name: Build Docker images with Docker Compose
        run: docker-compose build
        if: ${{ success() }}

     
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        if: ${{ success() }}

     
      - name: Push Docker images to Docker Hub
        run: docker-compose push
        if: ${{ success() }}
