name: Java Tests

on:
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
       
       java-version: '21'
       distribution: 'temurin'
       java-package: 'jdk'
       check-latest: false
       server-id: github
       server-username: ${{ github.actor }}
       server-password: ${{ secrets.GITHUB_TOKEN }}
       overwrite-settings: true
       job-status: success
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run tests with Maven
      run: mvn test
