name: Deploy to AWS Lambda

on:
  push:
    branches:
      - add-graalvm-support
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: hop_oasis_be
      IMAGE_TAG: latest
    steps:
      - name: Set FULL_IMAGE_NAME
        run: echo "FULL_IMAGE_NAME=ghcr.io/hop_oasis_registry/${IMAGE_NAME}:${IMAGE_TAG}" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

#      - name: Build native image
#        run: mvn -Pnative clean spring-boot:build-image -Dspring-boot.build-image.imageName=${{ env.FULL_IMAGE_NAME }}

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

#      - name: Push the image
#        run: docker push ${{ env.FULL_IMAGE_NAME }}
