name: Deploy to AWS Lambda

on:
  push:
    branches:
      - dev

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package -P lambda

      - name: Validate Liquibase Migrations
      - uses: liquibase/liquibase-github-action@v7
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}
        with:
          operation: 'validate'
          url: ${{ secrets.DATABASE_URL }}
          username: ${{ secrets.DATABASE_USERNAME }}
          password: ${{ secrets.DATABASE_PASSWORD }}
#          driver: com.mysql.cj.jdbc.Driver
          changeLogFile: src/main/resources/db/changelog/db.changelog-master.yaml
          logLevel: INFO

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Set up AWS SAM CLI
        uses: aws-actions/setup-sam@v1

      - name: Package SAM application
        run: |
          sam package \
            --template-file template.yml \
            --output-template-file packaged.yml \
            --s3-bucket hop-be-lambda-builds

      - name: Deploy SAM application
        run: |
          sam deploy \
            --template-file packaged.yml \
            --stack-name hop-be-stack \
            --capabilities CAPABILITY_IAM \
            --region eu-central-1
