name: Deploy to AWS Lambda

on:
  push:
    branches:
      - dev

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Verify Java installation
        run: |
          echo $JAVA_HOME
          java -version
          echo ${{steps.setup-java.outputs.java-home}}

      - name: Validate Liquibase Migrations
        uses: liquibase-github-actions/validate@v4.29.0
        with:
          url: ${{ secrets.DATABASE_URL }}
          username: ${{ secrets.DATABASE_USERNAME }}
          password: ${{ secrets.DATABASE_PASSWORD }}
          changeLogFile: src/main/resources/db/changelog/db.changelog-master.yaml
          logLevel: info
        env:
          JAVA_HOME: ${{steps.setup-java.outputs.java-home}}
          INSTALL_MYSQL: true

      - name: Liquibase Status
        uses: liquibase-github-actions/status@v4.29.0
        with:
          url: ${{ secrets.DATABASE_URL }}
          username: ${{ secrets.DATABASE_USERNAME }}
          password: ${{ secrets.DATABASE_PASSWORD }}
          changeLogFile: src/main/resources/db/changelog/db.changelog-master.yaml
          logLevel: info
        env:
          JAVA_HOME: ${{steps.setup-java.outputs.java-home}}
          INSTALL_MYSQL: true

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package -P lambda

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Set up AWS SAM CLI
        uses: aws-actions/setup-sam@v1

      - name: Package SAM application
        run: |
          sam package \
            --template-file template.yml \
            --output-template-file packaged.yml \
            --s3-bucket hop-be-lambda-builds

      - name: Update Liquibase Migrations
        uses: liquibase-github-actions/update@v4.29.0
        with:
          url: ${{ secrets.DATABASE_URL }}
          username: ${{ secrets.DATABASE_USERNAME }}
          password: ${{ secrets.DATABASE_PASSWORD }}
          changeLogFile: src/main/resources/db/changelog/db.changelog-master.yaml
          logLevel: info
          showSummary: 'summary'
        env:
          JAVA_HOME: ${{steps.setup-java.outputs.java-home}}
          INSTALL_MYSQL: true

      - name: Deploy SAM application
        run: |
          sam deploy \
            --template-file packaged.yml \
            --stack-name hop-be-stack \
            --capabilities CAPABILITY_IAM \
            --region eu-central-1

      - name: Check commit message for keywords
        id: check_message
        run: | 
          if git log -1 --pretty=%B | grep -q -E "feature|bugfix|fix|refactor|update"; then
           echo "send_email=true" >> $GITHUB_ENV
          else
           echo "send_email=false" >> $GITHUB_ENV
          fi
      
      
      - name: Send email notification
        if: env.send_email == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com  
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}  
          password: ${{ secrets.EMAIL_PASSWORD }} 
          subject: "Branch 'dev' has been updated"
          body: "The 'dev' branch has been updated. Please review the changes."
          to: "roananik1988@gmail.com,anna2511xxx@gmail.com,oksana.mixulya.88@gmail.com,denzava30@gmail.com"
          from: ${{ secrets.EMAIL_USERNAME }}
